#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_bundle:
  resource: "@UserBundle/Resources/config/routing.yaml"

user_admin:
  resource: "@UserBundle/Controller/Administration/"
  type: annotation
  prefix: /admin
